# @package _global_
save_dir: models/
resume:
status: train

n_gpu: 1
n_cpu: 8
trainer:
  epochs: 20
  logging_step: 100

  monitor: min loss/valid
  save_topk: 7
  early_stop: 10

  tensorboard: true
