log_dir: ${name}/
resume:

metrics:

defaults:
  - data: tacotron_train
  - model: tacotron
  - hparams: tacotron

  - status: train

  - override hydra/job_logging : custom
  # - hydra/run/dir: job_timestamp
